name: jachei_app
description: "App de catálogo de serviços Jachei"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Dependências identificadas pelos erros:
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  get_it: ^7.6.0
  injectable: ^2.3.2
  shared_preferences: ^2.2.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.13.1
  uuid: ^4.5.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Necessários para gerar o código do injectable:
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_app.png"
  min_sdk_android: 21 # Opcional, mas recomendado para o Android
  web:
    generate: true
    image_path: "assets/images/logo_app.png"